name: Trigger auto deployment for fe

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/fe-AutoDeployTrigger-ce249d18-598c-49ea-ad31-a7a61fc6dc08.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: aca42.azurecr.io
          username: ${{ secrets.FE_REGISTRY_USERNAME }}
          password: ${{ secrets.FE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: aca42.azurecr.io/fe:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n fe -g aca42 --server aca42.azurecr.io --username  ${{ secrets.FE_REGISTRY_USERNAME }} --password ${{ secrets.FE_REGISTRY_PASSWORD }}
            az containerapp update -n fe -g aca42 --image aca42.azurecr.io/fe:${{ github.sha }}
